### ISSUE TITLE
Variant checksum mismatch

### ISSUE THREAD

**Issue by Lostmp5** [zephyrj/sim-racing-tools#13]
![image](https://user-images.githubusercontent.com/83926241/190860991-63e0701f-446b-4a49-b2b3-bbbe18e748de.png)
I now have this new error message, it only works when i reset automation.

**Comment by zephyrj** [comment]
Hi, 

See: https://sykology.dev/fixing-problems/
> This is currently a limitation of how the engine data needs to be gathered; to get all the info engine-crane needs it gets some data from the BeamNG mod and some from the Automation data stored in its database. This error can occur if you change an engine in the Automation UI after you have created a mod from it - the Automation database is updated but the mod will contain outdated engine data.
You can fix this by creating a new mod with the latest update of your engine and using that to perform the swap

I've updated this handling to be more specific about where the mismatch is. You can pick up the latest version at either:
- https://github.com/zephyrj/engine-crane/releases
- https://sykology.dev/downloads/

Would it be possible to raise future issues on https://github.com/zephyrj/engine-crane/issues please? That way this info will be linked to the correct repository

**Comment by zephyrj** [comment]
Oh, would you be able to tell me if you get the same Window virus error when trying to get the latest release? If you can tell me what it gets classified as again that would be very helpful as I can put in a request to Microsoft that the file isn't malicious here: https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by Lostmp5** [comment]
Ok, i will write future issues on https://github.com/zephyrj/engine-crane/issues. 
![image](https://user-images.githubusercontent.com/83926241/190880196-b002e26d-3390-4773-af75-912b1d8f43dd.png)
The file gets detected as Trojan:Script/Wacatac.H!ml i dont know what that means. I Always make a new mod but the error keeps reapearing.

**Comment by zephyrj** [comment]
What does the error message say the mismatch is on? V0.1.5 should indicate what attribute it is failing the check on

Could you send me the engine_crane.log file for me to look at? It will have been created in the same directory where engine-crane is run.

**Comment by Lostmp5** [comment]
first it worken on 1.15 but now i get this error
![image](https://user-images.githubusercontent.com/83926241/191133593-51ff0e3e-0328-44dc-b965-b917d2758cf5.png)

**Comment by Lostmp5** [comment]
[engine_crane.log](https://github.com/zephyrj/sim-racing-tools/files/9602824/engine_crane.log)

**Comment by Lostmp5** [comment]
also it doesnt remember where your assetto corsa folder is

**Comment by zephyrj** [comment]
I'll update the code to print a better error message for this to try and work out what's going on

**Comment by zephyrj** [comment]
Try 0.1.6 - this should give a better error message that we can work with
https://github.com/zephyrj/engine-crane/releases/tag/v0.1.6-alpha

**Comment by Lostmp5** [comment]
Now with 1.6 it works again

**Comment by zephyrj** [comment]
Cool - that's great. I'm not sure what I've changed to make it work (there's very little changed) but I'm glad it's working for you
